### ISSUE TITLE
Please bump sglang version

### ISSUE THREAD

**Issue by hongbo-miao** [allenai/olmocr#245]
### 🐛 Describe the bug

When I try to use uv to install

```toml
[project]
name = "hm-olmocr"
version = "1.0.0"
requires-python = "~=3.12.0"
dependencies = [
  "olmocr[gpu]==0.1.71",
]

[tool.uv]
package = false
required-version = ">=0.6.0"

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
```

I got error:

```
  × No solution found when resolving dependencies:
  ╰─▶ Because flashinfer was not found in the package registry and sglang[all]==0.4.2 depends on flashinfer==0.1.6, we can conclude that sglang[all]==0.4.2 cannot be used.
      And because olmocr[gpu]==0.1.71 depends on sglang[all]==0.4.2 and your project depends on olmocr[gpu]==0.1.71, we can conclude that your project's requirements are unsatisfiable.
```

This is because `flashinfer` renamed to `flashinfer-python`, sglang needs to be at least 0.4.3 to use `flashinfer-python`.

Would you mind upgrading sglang to 0.4.3 or above? Thank you! ☺️

### Versions

3.12.0
