### ISSUE TITLE
Support NVIDIA Blackwell architecture

### ISSUE THREAD

**Issue by hongbo-miao** [allenai/olmocr#247]
# Experiment 1

I try to run on GeForce RTX 5090 (NVIDIA Blackwell) using uv.
olmocr is using an old sglang, so I try to install sglang separately like `sglang[blackwell]`:
 
```tmol
[project]
name = "hm-olmocr"
version = "1.0.0"
requires-python = "~=3.11.0"
dependencies = [
  "olmocr==0.1.71",
  "sglang[blackwell]==0.4.7",
]

[tool.uv]
package = false
required-version = ">=0.6.0"
```

To reproduce, you can run:

```sh
curl -o olmocr-sample.pdf https://olmocr.allenai.org/papers/olmocr_3pg_sample.pdf
uv run python -m olmocr.pipeline ./localworkspace --markdown --pdfs olmocr-sample.pdf
```

However, I got error:

```sh
uv sync
  × No solution found when resolving dependencies:
  ╰─▶ Because olmocr==0.1.71 depends on transformers==4.46.2 and sglang[blackwell]==0.4.7 depends on transformers==4.52.3, we can conclude that olmocr==0.1.71 and sglang[blackwell]==0.4.7 are incompatible.
      And because your project depends on olmocr==0.1.71 and sglang[blackwell]==0.4.7, we can conclude that your project's requirements are unsatisfiable.
error: Recipe `uv-install-dependencies` failed on line 5 with exit code 1
```

It would be great to support NVIDIA Blackwell architecture, thanks! ☺️

# Experiment 2 (Docker way)

I also tried Docker way

```sh
docker run -it --gpus all \
  -v /path/to/your/local/files:/local_files \
  --name olmocr_container \
  alleninstituteforai/olmocr:v0.1.71 /bin/bash
```

However, you can see in the middle, PyTorch had issue.
In this case PyTorch needs to be new version and set `https://download.pytorch.org/whl/cu128`, more info can be found [here](https://github.com/lllyasviel/Fooocus/issues/3862).

Here is full log: https://gist.github.com/hongbo-miao/fe51beaa5faa2477ddb72c42e1914d96

**Comment by hongbo-miao** [comment]
Thank you @jakep-allenai !

This is latest version I tried

```toml
[project]
name = "hm-olmocr"
version = "1.0.0"
requires-python = "~=3.11.0"
dependencies = [
  "olmocr==0.1.75",
  "torch==2.7.1",
]

[tool.uv]
package = false
required-version = ">=0.6.0"

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
```

`torch` has to use `https://download.pytorch.org/whl/cu128` to support Blackwell architecture.

But I think it is getting close! ☺️

I believe right now need wait vLLM fully support Blackwell architecture, I only succeed in Docker way: https://github.com/vllm-project/vllm/issues/14452#issuecomment-2972616954
